/**
 * Admin feature coverage checklist (storefront + API + admin UI).
 * status: done | partial | missing
 */
export const FEATURE_COVERAGE = [
  { area: "Storefront home / about / contact", reference: "/", status: "partial", notes: "React pages exist; marketing assets may need refresh." },
  { area: "Auth login / register / logout", reference: "/login, /register, /logout", status: "done", notes: "Session API + React." },
  { area: "Forgot password", reference: "/forgot-password", status: "missing", notes: "Placeholder UI; email reset flow not implemented." },
  { area: "Account dashboard / profile", reference: "/account", status: "partial", notes: "Profile + orders; confirm all account fields." },
  { area: "Categories / category / products / search / product", reference: "/categories, /category/:slug, …", status: "done", notes: "Mongo-backed APIs." },
  { area: "Cart (add/update/remove/clear/count/buy-now)", reference: "/cart/*", status: "done", notes: "REST cart routes." },
  { area: "Checkout + success", reference: "/checkout", status: "done", notes: "Coupon in placeOrder body; no separate mid-checkout apply-coupon step." },
  { area: "Customer orders + detail", reference: "/orders, /order/:num", status: "done", notes: "GET /api/orders, /api/order/:num." },
  { area: "Customer order cancel", reference: "POST /order/cancel", status: "done", notes: "POST /api/order/cancel + order detail (Pending/Confirmed only)." },
  { area: "Wishlist", reference: "/wishlist", status: "done", notes: "" },
  { area: "Reviews (storefront submit)", reference: "POST /reviews", status: "done", notes: "" },
  { area: "Policies (refund/privacy/shipping/terms)", reference: "Legal pages", status: "missing", notes: "PolicyPage placeholders." },
  { area: "Admin dashboard", reference: "/admin", status: "done", notes: "AdminDashboard + stats from Mongo aggregates." },
  { area: "Admin help", reference: "/admin/help", status: "done", notes: "AdminHelpPage." },
  { area: "Admin analytics", reference: "/admin/analytics", status: "partial", notes: "Mongo aggregates; UTC calendar days." },
  { area: "Admin categories CRUD", reference: "/admin/categories", status: "done", notes: "" },
  { area: "Admin brands CRUD", reference: "/admin/brands", status: "done", notes: "" },
  { area: "Admin models CRUD", reference: "/admin/models", status: "done", notes: "" },
  { area: "Admin subcategories + toggle", reference: "/admin/subcategories", status: "done", notes: "" },
  { area: "Admin products CRUD + images", reference: "/admin/products", status: "partial", notes: "Editor + Cloudinary queue; image manager merged into editor." },
  { area: "Admin product per-store stock page", reference: "/admin/products/:id/stock", status: "missing", notes: "Use stock-management / variant stock or add dedicated page." },
  { area: "Admin product variant-only routes", reference: "/admin/products/:id/variant/*", status: "partial", notes: "Variants inside ProductEditor." },
  { area: "Admin TSPL / printers", reference: "/admin/printers, print routes", status: "partial", notes: "print/tspl + JSPM in product editor." },
  { area: "Admin orders list", reference: "/admin/orders", status: "partial", notes: "Date range + status + search; store filter via order line → product not implemented." },
  { area: "Admin order detail + status", reference: "/admin/orders/:id", status: "done", notes: "PATCH statuses; shortcuts to returns/POS." },
  { area: "Admin order → POS billing preload", reference: "/admin/orders/:id/billing", status: "missing", notes: "Pre-filled POS cart needs a dedicated API; POS cart is separate today." },
  { area: "Admin order print barcodes", reference: "/admin/orders/:id/print-barcodes", status: "missing", notes: "Use product/variant TSPL flows." },
  { area: "Admin reviews moderation", reference: "/admin/reviews", status: "done", notes: "" },
  { area: "Admin returns (web+POS bill)", reference: "/admin/returns", status: "partial", notes: "Web lines use order_line_index; numeric order_item_id not mapped." },
  { area: "Admin coupons", reference: "/admin/coupons", status: "done", notes: "Admin-only." },
  { area: "Admin POS", reference: "/admin/pos/*", status: "partial", notes: "Core billing; some utility/backfill routes not exposed." },
  { area: "Admin stock transfer", reference: "/admin/stock/transfer", status: "done", notes: "React path /admin/stock-transfer." },
  { area: "Admin stock management", reference: "/admin/stock-management", status: "done", notes: "" },
  { area: "Admin stores / counters / staff / roles", reference: "CRUD", status: "done", notes: "Role assign-user extras — verify RoleEditor." },
  { area: "Admin attendance", reference: "/admin/attendance/*", status: "partial", notes: "Check-in/out + board + mark; reports/export/role depth TBD." },
  { area: "Admin income & expense", reference: "/admin/income-expense/*", status: "partial", notes: "Mongo ledgers; UTC date keys; REST paths." },
  { area: "Admin test route", reference: "/test", status: "missing", notes: "Dev-only; optional /api/dev/test." },
  { area: "Feature coverage (this page)", reference: "—", status: "done", notes: "/admin/feature-coverage — internal checklist." },
];
